<?php
error_reporting(0);
include 'Warehouse.php';
// DEFAULT
if(User('PROFILE')=='admin')
	$help['default'] = '<p>Como administrador, usted puede crear las instituciones en el sistema, modificar estudiantes y usuarios, y acceder a los reportes esenciales sobre los estudiantes.</p><p>Usted tiene acceso a cualquier institución en el sistema. Para escoger una institución para trabajar, seleccione la institución desde el menú desplegable en el marco izquierdo. El programa refrescara automáticamente el espacio de trabajo con la nueva institución. De la misma manera, usted también puede cambiar el año escolar y el periodo a calificar.</p><p>Usando RosarioSIS, usted vera aparecer otras opciones en el marco izquierdo. Cuando usted selecciona un estudiante para trabajar, el nombre del estudiante aparece debajo del menú desplegable del periodo a calificar. Cambiando de servicio, usted sigue trabajando con el estudiante. Si usted quiere trabajar con otro estudiante, haga click sobre la cruz roja al lado del nombre del estudiante. Usted también puede acceder rápidamente a los Datos Personales del estudiante haciendo click sobre el nombre del estudiante. Igualmente ocurre, cuando usted selecciona un usuario para trabajar.</p><p>Cuando usted hace click sobre cualquier icono del marco izquierdo, podrá ver una lista de los servicios disponibles en el módulo. Haciendo click sobre cualquier titulo de servicio, este se abrirá en el marco principal, y se actualizará el marco de ayuda (abajo).</p><p>En muchos lugares de RosarioSIS, usted podrá ver listas de datos que están modificables. A menudo, usted deberá hacer click primero sobre el dato que usted quiere cambiar para tener acceso a el campo de entrada.</p><p>Usted puede salir de RosarioSIS en cualquier momento haciendo click sobre el enlace «Salir» en el marco inferior.</p>';
elseif(User('PROFILE')=='teacher')
	$help['default'] = '<p>Como docente, usted puede ver datos de los estudiantes y horarios de los estudiantes que tiene, y con los cuales usted trabaja asistencia, calificaciones y elegibilidad. Usted tiene también un servicio de libro de calificaciones para hacer seguimiento de las calificaciones. El Libro de Calificaciones esta integrado en el servicio Entrar Calificaciones Finales como también en el servicio Elegibilidad. Desde el Libro de Calificaciones, Usted también puede imprimir reportes de progreso par cualquier de sus estudiantes.</p><p>Para escoger una clase para trabajar, seleccionela en el menú desplegable del marco izquierdo. El programa refrescara automáticamente el espacio de trabajo con la nueva clase. De la misma manera, usted puede también cambiar el año escolar y el periodo a calificar.</p><p>Usando RosarioSIS, usted vera aparecer otras opciones en el marco izquierdo. Cuando usted selecciona un estudiante para trabajar, el nombre del estudiante aparece debajo del menú desplegable del periodo a calificar. Moviendose entre los servicios, usted sigue trabajando con el estudiante. Si usted quiere trabajar con otro estudiante, haga click sobre la cruz roja al lado del nombre del estudiante. Usted también puede acceder rápidamente a los Datos Personales del estudiante haciendo click sobre el nombre del estudiante.</p><p>Cuando usted hace click sobre cualquier icono del marco izquierdo, usted podrá ver una lista de los servicios disponibles para usted en el módulo. Haciendo click sobre cualquier título de servicio, este se abrirá en el marco principal, y se actualizara el marco de ayuda (abajo).</p><p>En el libro de calificaciones, usted podrá ver listas de datos que están modificables. A menudo, usted deberá hacer click primero sobre el dato que usted quiere cambiar para tener acceso a un campo de entrada.</p><p>Usted puede salir de RosarioSIS en cualquier momento haciendo click sobre el enlace «Salir» en el marco inferior.</p>';
elseif(User('PROFILE')=='parent')
	$help['default'] = '<p>Como padre, usted puede ver los datos de sus estudiantes, los horarios, la elegibilidad, y la asistencia.</p><p>Para escoger un estudiante, seleccione el nombre del estudiante en el menú desplegable en el marco izquierdo. El programa refrescara automáticamente el espacio de trabajo con el nuevo estudiante. De la misma manera, usted puede también cambiar el año escolar y el periodo a calificar.</p><p>Usando RosarioSIS, usted vera aparecer otras opciones en el marco izquierdo. Cuando usted hace click sobre cualquier icono del marco izquierdo, podrá ver una lista de los programas disponibles para usted en el módulo. Haciendo click sobre cualquier titulo de servicio, este se abrirá en el marco principal, y se actualizara el marco de ayuda (abajo).</p><p>Usted puede salir de RosarioSIS en cualquier momento haciendo click sobre el enlace «Salir» en el marco inferior.</p>';
elseif(User('PROFILE')=='student')
{
	$help['default'] = '<p>Como estudiante, usted puede ver sus datos, horario, calificaciones, elegibilidad, y asistencia.</p><p>Usted puede cambiar el año escolar y el periodo a calificar en los menús desplegables en el marco izquierdo.</p><p>Usando RosarioSIS, usted vera aparecer otras opciones en el marco izquierdo. Cuando usted hace click sobre cualquier icono del marco izquierdo, usted podrá ver una lista de los servicios disponibles para usted en el módulo. Haciendo click sobre cualquier titulo de servicio, este se abrirá en el marco principal, y se actualizara el marco de ayuda (abajo).</p><p>Usted puede salir de RosarioSIS en cualquier momento haciendo click sobre el enlace «Salir» en el marco inferior.</p>';
}

// SCHOOL SETUP ---
if(User('PROFILE')=='admin')
{
	$help['School_Setup/Schools.php'] = '<p><i>Información de la Institución</i> le permite cambiar el nombre, la dirección y el director de la institución. Haga click sobre cualquier dato para cambiarlo. Después de haber hecho los cambios necesarios para su institución, presione el botón «Guardar» para guardar sus cambios.</p>';
	$help['School_Setup/Schools.php&new_school=true'] = '<p><i>Agregar una Institución</i> le permite agregar una institución al sistema. Llena los datos de la institución, y presiona el botón «Guardar».</p><p>Para cambiar a la nueva institución, cambie el menú desplegable de las instituciones en el marco izquierdo.</p>';
	$help['School_Setup/MarkingPeriods.php'] = '<p><i>Períodos a Calificar</i> le permite configurar los períodos a calificar de la institución. Hay tres tercios de períodos a calificar: algo como Semestres, Bimestres y Períodos intermedios esta sugerido. A pesar de sus nombres, puede ser menos de 2 semestres y mas o menos de 4 bimestres.</p><p>Para agregar un período a calificar, haga click sobre el icono «+» en la columna del tipo de período a calificar que usted quiere agregar. Luego, completa los datos del período a calificar en los campos de arriba y presione el botón «Guardar».</p><p>Para cambiar un período a calificar, haga click sobre el período a calificar que usted quiere cambiar, y haga click sobre cualquier valor que usted quiere cambiar en la zona de arriba. Luego, cambie el valor y presione el botón «Guardar».</p><p>Para eliminar un período a calificar, seleccione lo haciendo click sobre su titulo en la lista y presione el botón «Eliminar» en la parte superior de la pantalla. Se le preguntará si desea confirmar la eliminación.</p><p>Note que dos períodos a calificar o dos periodos de publicación de calificaciones no se pueden cruzar. También, los períodos a calificar de un mismo tercio deben tener un orden diferente.</p>';
	$help['School_Setup/Calendar.php'] = '<p><i>Calendario</i> le permite configurar el calendario de su institución para el año. El calendario muestra el mes actual por defecto. El mes y el año mostrado se pueden cambiar en los menús desplegables del mes y del año en la parte superior de la pantalla.</p><p>En días completos de institución, la casilla en la esquina superior derecha del día debería estar marcada. Para los días parciales, la casilla no debería estar marcada y el número de minutos de asistencia a la institución, debería estar en el campo de texto al lado de la casilla. Para los días sin institución, la casilla no debería estar marcada y el campo de texto vacío. Para desactivar la casilla o cambiar el número de minutos en el día, usted debe primero hacer click sobre el valor que desee cambiar. Después de hacer un cambio al calendario, presione el botón «Actualizar» en la parte superior de la pantalla.</p><p>Si la institución usa una rotación de días enumerados, el numero del día aparece en el cuadro de los días de institución.</p><p>Para configurar su calendario al comienzo del año, usted debería usar «Crear un nuevo calendario». Haciendo click sobre este enlace, usted puede configurar todos los días en un transcurso especificado como días completos de clase. Usted puede también seleccionar cuales días de la semana su institución trabaja. Después de seleccionar las fechas de comienzo y fin del año escolar y los días de trabajo de la institución, presione el botón «OK». Usted ya puede navegar por el calendario y marcar las vacaciones y días parciales.</p><p>El calendario muestra también los eventos de la institución. Esto puede incluir todo, desde los días de servicio de los docentes hasta los eventos de deporte. Estos eventos están visibles por los otros administradores y también por los padres y docentes de la institución.</p><p>Para agregar un evento, haga click sobre el icono «+» en la esquina inferior izquierda de la fecha del evento. En la ventana emergente que aparece, entrar los datos del evento y presione el botón «Guardar». La ventana emergente se cerrara, y el calendario será actualizado para mostrar el evento agregado.</p><p>Para cambiar un evento, haga click sobre el evento que quiere modificar, y cambie los datos del evento en la ventana emergente que aparece. Luego, presione el botón «Guardar». La ventana se cerrara y el calendario será actualizado para mostrar el cambio.</p>';
	$help['School_Setup/Periods.php'] = '<p><i>Horas</i> le permite configurar las horas de la institución.</p><p>Para agregar una hora, llene el titulo de la hora, su nombre corto, orden, y duración en minutos en los campos vacíos al pié de la lista de horas y presione el botón «Guardar».</p><p>Para cambiar una hora, haga click sobre cualquiera dato de la hora, cambie el dato, y presione el botón «Guardar».</p><p>Para eliminar una hora, haga click sobre el icono «-» al lado de la hora que quiere eliminar. Se le preguntará si desea confirmar la eliminación.</p>';
	$help['School_Setup/GradeLevels.php'] = '<p><i>Grados</i> le permite configurar los grados de su institución.</p><p>Para agregar un grado, llene el titulo del grado, su nombre corto, orden, y grado siguiente en los campos vacíos al pié de la lista de grados y presione el botón «Guardar». El campo «Grado Siguiente» indica el grado al cual pasarán los estudiantes en el año escolar siguiente.</p><p>Para cambiar un grado, haga click sobre cualquier dato del grado, cambie el valor, y presione el botón «Guardar».</p><p>Para eliminar un grado, haga click sobre el icono «-» al lado del grado que quiere eliminar. Se le preguntará si desea confirmar la eliminación.</p>';
	$help['School_Setup/Rollover.php'] = '<p><i>Transferir</i> copia los datos del año actual al siguiente año escolar. Los estudiantes están matriculados en el siguiente grado, y cada dato de la institución esta duplicado para el año siguiente.</p><p>Los datos copiados incluyen horas, períodos a calificar, usuarios, cursos, matrícula de los estudiantes, códigos de grados del boletín de calificaciones, códigos de matricula, códigos de asistencia, y actividades de elegibilidad.</p>';
}
else
{
	$help['School_Setup/Schools.php'] = '<p><i>Información de la Institución</i> muestra el nombre, la dirección, y el director de la institución.</p>';
	$help['School_Setup/Calendar.php'] = '<p><i>Calendario</i> muestra los eventos de la institución y las tareas de sus estudiantes. El calendario muestra también los días de institución. Por defecto, el calendario muestra el mes actual. El mes y el año mostrados pueden ser cambiados en los menús desplegables del mes y del año en la parte superior de la pantalla.</p><p>Los títulos de los eventos y  de las tareas están en cada caja del día. Haciendo click sobre estos títulos abrirá una ventana emergente que muestra mas información sobre el evento o la tarea.</p><p>En días completos de institución, el día aparece en verde. Para los días parciales, el número de minutos de asistencia en la institución aparece en la esquina superior derecha. Para los días sin institución, el día aparece en rosado.</p><p>Si la institución usa una rotación de días enumerados, el número del día aparece en la caja de los días de institución.</p>';
}

// STUDENTS ---
if(User('PROFILE')=='admin')
{
	$help['Students/Student.php&include=General_Info&student_id=new'] = '<p><i>Agregar un Estudiante</i> le permite agregar un estudiante y matricularlo.</p><p>Para agregar el estudiante, entre su fecha de nacimiento, etnicidad, sexo, lugar de nacimiento y grado. Luego, seleccione la fecha de matricula del estudiante y el código de matricula desde el menú desplegable al pié de la pagina. Si usted quiere especificar un ID para este estudiante, entre lo en el campo de texto «ID RosarioSIS». Si usted deja este campo blanco, RosarioSIS generara un ID para el estudiante. Finalmente, presione el botón «Guardar» en la parte superior de la pantalla.</p>';
	$help['Students/AssignOtherInfo.php'] = '<p><i>Asignar Información de Estudiante en Conjunto</i> lle permite asignar datos a cualquier campo de dato a un grupo de estudiantes de una vez.</p><p>Primero, busca estudiantes. Desde el resultado de la búsqueda, usted puede seleccionar cualquier número de estudiantes. Usted puede seleccionar todos los estudiantes de la lista marcando la casilla en el encabezado de la lista. Después de seleccionar estudiantes, llene cualquier de los campos de datos de arriba. Los campos que están en blanco no afectaran los estudiantes seleccionados. Finalmente, presione el botón «Guardar» en la parte superior de la pantalla.</p>';
	$help['Students/Letters.php'] = '<p><i>Imprimir Cartas</i> le permite imprimir un modelo de carta para varios estudiantes.</p><p>Primero, busca estudiantes. Después de seleccionar estudiantes desde el resultado de la búsqueda, entre el texto de la carta en el campo de texto «Texto de la Carta». Arriba de este campo de texto se encuentran varias opciones de formato del texto.</p><p>Usted puede insertar algunos datos del estudiante en la carta con variables especiales:<UL><LI><b>Nombre Completo:</b> __FULL_NAME__</LI><LI><b>Nombre:</b> __FIRST_NAME__</LI><LI><b>Segundo Nombre:</b> __MIDDLE_NAME__</LI><LI><b>Apellido:</b> __LAST_NAME__</LI><LI><b>ID RosarioSIS:</b> __STUDENT_ID__</LI><LI><b>Institución:</b>
	__SCHOOL_ID__</LI><LI><b>Grado:</b> __GRADE_ID__</LI><LI><b>Docente de Asistencia:</b>	__TEACHER__</LI><LI><b>Salón de Asistencia:</b>	__ROOM__</LI></UL></p><p>También puede escoger imprimir la cartas con etiquetas de correo. Las cartas tendrán etiquetas de correo posicionadas de una manera visible para un sobre con ventana cuando la hoja esta doblada en tercios. Mas de una carta puede ser impreza por estudiante si el estudiante tiene padres residiendo en mas de una dirección.</p><p>Las cartas serán automáticamente creadas en el formato imprimible PDF cuando usted presione el botón «Enviar».</p>';
	$help['Students/Student.php&include=General_Info'] = '<p><i>Datos Personales</i> muestra los datos fundamentales del estudiante. Usted puede cambiar cualquier dato haciendo click sobre el valor que quiere cambiar, cambiando el valor, y presionando el botón «Guardar» en la parte superior de la pantalla.</p>';
	$help['Students/Student.php&include=Address'] = '<p><i>Direcciones & Contactos</i> muestra las direcciones y los contactos del estudiante.</p><p>Un estudiante puede tener mas de una dirección. Para agregar una dirección, llene los campos vacíos abajo, y presione el botón «Guardar» en la parte superior de la pantalla.</p><p>Ahora, usted puede agregar un contacto a esta dirección. Para hacerlo, llene el nombre del contacto, y presione el botón «Guardar».</p><p>Usted puede ahora añadir mas información sobre este contacto marcando las casillas «Custodia» y «Emergencia» después de hacer click sobre la cruz roja. Los contactos marcados como «Custodia» del estudiante reciben los correos, y los contactos marcados como «Emergencia» pueden ser contactados en caso de emergencia.</p><p>Usted puede agregar otras informaciones sobre este contacto, como su teléfono, profesión, etc.</p><p>Contactos e informaciones sobre un contacto pueden ser eliminados haciendo click sobre el icono «-» al lado de la información a eliminar. Cualquier información en la pantalla puede ser modificada haciendo click sobre la información primero, luego cambiando el dato, y finalmente presionando el botón «Guardar» en la parte superior de la pantalla.</p>';
	$help['Students/Student.php&include=Medical'] = '<p><i>Médico</i> muestra la información médica de un estudiante.</p><p>Esta incluye el médico del estudiante, el teléfono del médico, el hospital preferido, cualquier comentario médico, si el estudiante tiene una calificación del médico o no, y comentarios sobre la calificación. Para cambiar cualquier valor, haga click sobre el dato que quiere cambiar, cambielo, y presione el botón «Guardar» en la parte superior de la pantalla.</p><p>Usted también puede agregar entradas para cada inmunización o chequeo que recibe el estudiante así como alertas médicas como enfermedades o alergias.</p><p>Para agregar una vacuna, un chequeo, o una alerta médica, llene los campos vacíos al final de la lista apropiada, y presione el botón «Guardar» en la parte superior de la pantalla.</p><p>Para cambiar una vacuna, un chequeo, o una alerta médica, haga click sobre el dato que desee cambiar, cambielo, y presione el botón «Guardar» en la parte superior de la pantalla.</p><p>Para eliminar una vacuna, un chequeo, o una alerta médica, haga click sobre el icono «-» al lado del artículo que quiere eliminar. Se le preguntará si desea confirmar la eliminación.</p>';
	$help['Students/Student.php&include=Other_Info'] = '<p><i>Other Info</i> is a student screen that allows you to keep any information about your students.  These fields can be changed or added to with the Data Fields setup program.</p><p>There are two types of Other Info fields: text fields and checkbox fields.  Text fields can store any text value up to 255 characters long.  Checkbox fields can be checked, indicating "Yes" or remain unchecked, indicating "No." Both types of fields can be changed by first clicking on the value, changing it to the desirable value, and clicking the "Save" button.</p>';
	$help['Students/Student.php&include=Enrollment'] = '<p><i>Matrícula</i> puede ser usado para matricular o retirar un estudiante de una institución. Un estudiante puede tener solamente una clave de matrícula activa a la vez.</p><p>Para retirar un estudiante, cambie la fecha y razón de «Retirado» para la fecha efectiva como la razón de su retiro. Presione el botón «Guardar» en la parte superior de la pantalla.</p><p>Usted puede ahora matricular de nuevo el estudiante. Para hacerlo, seleccione la fecha efectiva de matrícula del estudiante y la razón desde la linea blanca al fin de la lista. Seleccione también la institución donde el estudiante será matriculado y presione el botón «Guardar» en la parte superior de la pantalla.</p><p>Las fechas de matrícula y retiro y las razones se pueden cambiar haciendo click sobre los datos, cambiando los, y presionando el botón «Guardar» en la parte superior de la pantalla.</p>';
	$help['Students/StudentFields.php'] = $help['Students/PeopleFields.php'] = $help['Students/AddressFields.php'] = '<p><i>Campos de Estudiantes / Dirección / Contacto</i> le permite configurar campos de datos personalizados para su institución. Estos campos están usados para guardar información sobre un estudiante en las pantallas «Datos Personales» o «Direcciones y Contactos».</p><p>Hay cuatro tipos de campos de datos: texto, casilla, fecha y menú desplegable. Campos de texto pueden guardar cualquier dato de texto hasta 255 caracteres de largo. Casillas pueden ser macadas, indicando «Si» o vacías, indicando «No». Campos de fechas guardan fechas, y menús desplegables le permite seleccionar uno de los datos predeterminados.</p><p>Para agregar un campo de dato, llene el titulo y el tipo de dato del campo e dato. Si el campo es un menú desplegable, entre cada de las opciones disponibles en el campo «Menú Despegable/Menú Despegable Automático/Menú Despegable Codificado/Seleccionar», una por linea. Si no, deja este campo blanco. Presione el botón «Guardar».</p><p>Para cambiar un campo de dato, haga click sobre cualquier información del campo de dato, cambie el dato, y presione el botón «Guardar».</p><p>Para eliminar un campo de dato, haga click sobre el icono «-» al lado del campo de dato que quiere eliminar. Se le preguntará si desea confirmar la eliminación.</p>';
	$help['Students/EnrollmentCodes.php'] = '<p><i>Códigos de Matrícula</i> le permite configurar los códigos de matrícula de su institución. Los códigos de matrícula son usados en la pantalla de Matrícula del estudiante, y especifica la razón de matrícula o retiro de un estudiante de una institución. Estos códigos aplican para todas las instituciones del sistema.</p><p>Para agregar un código de matrícula, llene el titulo del código, su nombre corto, y tipo en los campos vacíos al fin de la lista de códigos de matrícula. Presione el botón «Guardar».</p><p>Para cambiar un código de matrícula, haga click sobre cualquiera información del código de matrícula, cambie el dato, y presione el botón «Guardar».</p><p>Para eliminar un código de matrícula, haga click sobre el icono «-» al lado del código de matrícula que quiere eliminar. Se le preguntará si desea confirmar la eliminación.</p>';
}
else
{
	$help['Students/Student.php&include=General_Info'] = '<p><i>Datos Personales</i> muestra los datos fundamentales del estudiante.</p>';
	$help['Students/Student.php&include=Address'] = '<p><i>Direcciones & Contactos</i> muestra las direcciones y los contactos del estudiante.</p><p>Un estudiante puede tener mas de una dirección.</p>';
	$help['Students/Student.php&include=Other_Info'] = '<p><i>Other Info</i> is a student screen that allows you to keep any information about students.  These fields can be changed or added to by an administrator with the Data Fields setup program.</p><p>There are two kinds of Other Info fields: text fields and checkbox fields.</p>';
	$help['Students/Student.php&include=Enrollment'] = '<p><i>Matrícula</i> muestra el historial de matrícula del estudiante.</p>';
}

// USERS
if(User('PROFILE')=='admin')
{
	$help['Users/User.php'] = '<p><i>Datos Personales</i> muestra los datos fundamentales de un usuario. Si usted es administrador, usted puede cambiar cualquier dato haciendo click sobre el dato que quiere cambiar, cambiando el dato, y presionando el botón «Guardar» en la parte superior de la pantalla. Usted puede eliminar un usuario presionando el botón «Eliminar» en la parte superior de la pantalla. Note que usted nunca debería eliminar un docente después que el ha dado una clase, porque el usuario debe quedar para que el nombre del docente pueda aparecer en los expedientes académicos.</p>';
	$help['Users/User.php&staff_id=new'] = '<p><i>Agregar un Usuario</i> le permite agregar un usuario al sistema. Esto incluye administradores, docentes y padres. Llena simplemente el nombre, nombre de usuario, perfil, institución, email y teléfono del usuario. Presione el botón «Guardar».</p>';
	$help['Users/AddStudents.php'] = '<p><i>Relacionar padres con Estudiantes</i> le permite relacionar estudiantes con padres.</p><p>Una vez que una cuenta de padre esta lista, sus estudiantes deben ser relacionados con este servicio. Si usted ya no ha seleccionado un usuario para la sesión, seleccione uno con la pantalla de búsqueda «Encontrar un Usuario». Luego, busque un estudiante para relacionar con la cuenta del usuario. Desde el resultado de la búsqueda, usted puede seleccionar cualquier número de estudiantes. Después de seleccionar cada estudiante deseado desde la lista, presione el botón «Agregar los Estudiantes Seleccionados» en la parte superior de la pantalla.</p><p>Después de seleccionar un usuario, usted puede ver los estudiantes que ya están relacionados con el usuario. Estos estudiantes pueden ser disociados de este usuario haciendo click sobre el icono «-» al lado del el estudiante. Se le preguntará si desea confirmar la acción.</p>';
	$help['Users/Exceptions.php'] = '<p><i>Permisos de Usuario</i> le permite prohibir acceso y/o privilegios de edición a cualquier servicio para un usuario con permisos configurados (Ver los Datos Personales del usuario).</p><p>Para asignar privilegios a un usuario, seleccionelo primero, y haga click sobre su nombre en la lista. Luego, use las casillas para definir cuales servicios el usuario puede visualizar y cuales servicios el puede editar. Si un usuario no puede usar un servicio especifico, este servicio no será mostrado en su menú. Si el usuario puede usar el servicio, pero no puede editar información con el servicio, el servicio mostrara los datos, pero no le dejara cambiar nada. Después de marcar las casillas, presione el botón «Guardar» para guardar los permisos.</p>';
	$help['Users/TeacherPrograms.php&include=Grades/InputFinalGrades.php'] = '<p><i>Programas Docente - Entrar Calificaciones Finales</i> le permite entrar la calificaciones de los bimestres, semestres, y exámenes de semestre para todos los estudiantes del docente seleccionado en la clase actual. Por defecto, el servicio listara los estudiantes de la primera clase del docente seleccionado para el bimestre actual. Usted puede cambiar la clase con el menú desplegable de las clases en la parte superior de la pantalla. Usted también puede cambiar el periodo a calificar con el menú desplegable de los periodos a calificar en el marco izquierdo. Además, usted puede seleccionar el semestre actual en el menú desplegable en la parte superior de la pantalla.</p><p>Una vez que usted esta en el periodo a calificar adecuado, usted puede entrar las calificaciones de los estudiantes seleccionando la calificación para cada estudiante y entrando comentarios como desee. Una vez que todas las calificaciones y los comentarios han sido entrados, presione el botón «Guardar» en la parte superior de la pantalla.</p><p>Si el docente seleccionado usa el Libro de Calificaciones, RosarioSIS puede calcular las calificaciones de cada estudiante para el bimestre haciendo click sobre el enlace «Obtener las Calificaciones del Libro de Calificaciones.» de arriba.</p>';
	$help['Users/TeacherPrograms.php&include=Attendance/TakeAttendance.php'] = '<p><i>Programas Docente - Tomar Asistencia</i> le permite entrar la asistencia de clase para todos los estudiantes del docente. Por defecto, este servicio listara los estudiantes de la primera clase del docente seleccionado. Usted puede cambiar la clase actual en el menú desplegable de las clases en la parte superior de la pantalla.</p><p>Una vez que usted esta en la clase adecuada, usted puede tomar la asistencia seleccionando el código de asistencia para cada estudiante. Una vez que la asistencia ha sido tomada para todos los estudiantes, presione el botón «Guardar» en la parte superior de la pantalla.</p>';
	$help['Users/TeacherPrograms.php&include=Eligibility/EnterEligibility.php'] = '<p><i>Programas Docente - Entrar Elegibilidad</i> le permite entrar calificaciones de elegibilidad para todos los estudiantes del docente seleccionado. Por defecto, este servicio listara los estudiantes de la primera clase del docente seleccionado. Usted puede cambiar la clase actual en el menú desplegable de las clases en la parte superior de la pantalla.</p><p>Una vez que usted esta en la clase adecuada, usted puede entrar la elegibilidad seleccionando el código de elegibilidad para cada estudiante. Una vez que la elegibilidad ha sido entrada para todos los estudiantes, presione el botón «Guardar» en la parte superior de la pantalla.</p><p>Si el docente seleccionado usa el Libro de Calificaciones, RosarioSIS puede calcular la elegibilidad de cada estudiante haciendo click sobre el enlace «Usar la Calificaciones del Libro de Calificaciones» de arriba.</p><p>Usted debe entrar la elegibilidad cada semana durante el transcurso especificado por el administrador de su institución.</p>';
}
// SCHEDULING
if(User('PROFILE')=='admin')
{
	$help['Scheduling/Schedule.php'] = '<p><i>Horario Estudiante</i> le permite cambiar el horario de un estudiante.<p>Usted debe primero seleccionar un estudiante usando la pantalla de búsqueda «Encontrar un Estudiante». Usted puede buscar estudiantes que han solicitado un curso especifico haciendo click sobre el enlace «Escoger» al lado de las opciones de búsqueda «Curso» y «Solicitud» y escogiendo un curso desde la ventana emergente que aparece.</p><p>Para agregar un curso al horario del estudiante, haga click sobre el enlace «Agregar un Curso» al lado del icono «+» y seleccione el curso desde la ventana emergente que aparece. La pantalla se refrescara automáticamente para mostrar el curso.</p><p>Para retirar un curso existente, haga click sobre el icono «-» al lado del curso que quiere retirar del horario del estudiante.</p><p>Para cambiar una clase de un curso de un estudiante, haga click sobre «Hora - Docente» del curso que quiere cambiar y seleccione la nueva clase. Usted también puede cambiar el periodo de la misma manera.</p><p>Todas las adiciones, eliminaciones, modificaciones al horario de un estudiante no permanecen a menos que usted presiona el botón «Guardar».</p>';
	$help['Scheduling/Requests.php'] = '<p><i>Solicitudes de Estudiante</i> le permite especificar cuales cursos un estudiante debe tomar para el siguiente año escolar. Esas solicitudes son usadas por el Programador para completar el horario de un estudiante.</p><p>Usted puede agregar una solicitud seleccionando el curso que usted quiere agregar buscando la materia. Usted puede agregar otras solicitudes desde cada materia de la misma manera. Una vez que usted ha agregado todas las solicitudes deseadas, presione el botón «Guardar» en la parte superior de la pantalla.</p><p>Además, usted tiene la posibilidad de especificar un docente o una hora y de excluir un docente o una hora. Para hacerlo, seleccione el docente o la hora desde los menús desplegables «Con» y «Sin».</p><p>Para eliminar una solicitud, haga click sobre el icono «-» al lado de la solicitud. Se le preguntará si desea confirmar la eliminación.</p>';
	$help['Scheduling/MassRequests.php'] = '<p><i>Asignar Varias Solicitudes</i> le permite agregar una solicitud a un grupo des estudiantes de una vez.</p><p>Primero, busque estudiantes. Note que usted puede buscar estudiantes que ya tienen una cierta solicitud o están en cierta actividad. Desde los resultados de la búsqueda, usted puede escoger cualquier número de estudiantes. Para seleccionar todos los estudiantes en la lista, marca la casilla en el encabezado de la lista. Luego, seleccione el curso para agregar como solicitud haciendo click sobre el enlace «Escoger un Curso» en la parte superior de la pantalla y escogiendo el curso desde la ventana emergente que aparece. Luego, presione el botón «Agregar Solicitud a los Estudiantes Seleccionados» en la parte superior de la pantalla.</p>';
	$help['Scheduling/ScheduleReport.php'] = '<p><i>Reporte de Horario</i> es un reporte que muestra los estudiantes programados en cada curso, los estudiantes que solicitaron el curso pero que no fueron programados, el número de solicitudes, los cupos abiertos, y el total de asientos en cada curso.</p><p>Para navegar en este reporte, haga click primero sobre una de las materias. Usted vera cada curso en esta materia también como el número de solicitudes para este curso, los cupos abiertos y el total de asientos. Si usted escoge un curso haciendo click sobre este, usted vera una lista de los estudiantes programados en este curso o una lista de los estudiantes que solicitaron el curso pero que no fueron programados haciendo click sobre el enlace «Listar Estudiantes no Programados».</p><p>Cualquier momento después de seleccionar una materia, usted puede navegar atrás haciendo click sobre los enlaces que aparezcan en la parte superior de la pantalla.</p>';
	$help['Scheduling/RequestsReport.php'] = '<p><i>Reporte de Solicitudes</i> es un reporte que muestra el número de estudiantes que solicitaron cada curso y el número total de asientos en este curso. Los cursos son agrupados por materia.</p><p>Ese reporte esta útil para crear el horario maestro porque le ayuda a determinar el número de clases necesario para cada curso en proporción a la demanda para el curso.</p>';
	$help['Scheduling/PrintSchedules.php'] = '<p><i>Imprimir Horarios</i> le permite imprimir los horarios para cualquier número de estudiantes.</p><p>Usted puede buscar estudiantes que solicitaron o están en un curso especifico haciendo click sobre el enlace «Escoger» al lado de las opciones «Solicitud» y «Curso» y escogiendo un curso desde la ventana emergente que aparece.</p><p>También puede escoger imprimir las solicitudes con etiquetas de correo. Las solicitudes tendrán etiquetas de correo posicionadas de una manera visible para un sobre con ventana cuando la hoja esta doblada en tercios. Mas de una carta puede ser impreza por estudiante si el estudiante tiene padres residiendo en mas de una dirección.</p><p>Las solicitudes serán automáticamente creadas en el formato imprimible PDF cuando usted presione el botón «Enviar».</p>';
	$help['Scheduling/PrintRequests.php'] = '<p><i>Imprimir Solicitudes</i> le permite imprimir hojas de solicitudes para cualquier número de estudiantes.</p><p>Se puede buscar estudiantes que solicitaron un curso especifico haciendo click sobre el enlace «Escoger» al lado de la opción «Solicitud» y escogiendo un curso desde la ventana emergente que aparece.</p><p>Also, you can choose to print the requests sheets with mailing labels.  The requests sheets will have mailing labels positioned in such a way as to be visible in a windowed envelope when the sheet is folded in thirds.  More than one request sheet may be printed per student if the student has guardians residing at more than one address.</p><p>The request sheets will be automatically downloaded to your computer in the printable PDF format when you click the \"Submit\" button.</p>';
	$help['Scheduling/Courses.php'] = '<p><i>Cursos</i> le permite configurar los cursos de su institución. Hay tres tercios: Materias, Cursos, Clases.</p><p>Para agregar cualquier de esos tres tercios, haga click sobre el icono «+» en la columna correspondiendo a lo que quiere agregar. Luego, llene la información necesaria en los campos arriba de las listas y presione el botón «Guardar».</p><p>Para cambiar cualquier de esos tres tercios, haga click sobre el articulo que quiere cambiar, y haga click sobre cualquier dato que quiere cambiar en la parte superior de las listas. Luego, cambie el dato y presione el botón «Guardar».</p><p>Finalmente, para eliminar algo, seleccione lo haciendo click sobre su titulo en la lista y presione el botón «Eliminar» en la parte superior de la pantalla. Se le preguntará si desea confirmar la eliminación.</p>';
	$help['Scheduling/Scheduler.php'] = '<p><i>Correr Programador</i> servicio cada estudiante en la institución siguiendo las solicitudes entradas para ellos.</p><p>Usted debe primero confirmar correr el Programador. Aquí, también puede escoger correr el Programador en «Modo de Prueba» que no guardara los horarios de los estudiantes.</p><p>Una vez que el programador ha corrido, lo que puede tomar algunos minutos, le mostrara las Solicitudes Incompletas.</p>';
}
elseif(User('PROFILE')=='teacher')
{
	$help['Scheduling/Schedule.php'] = '<p><i>Horario Estudiante</i> muestra el horario de los estudiantes.<p>Usted debe primero seleccionar un estudiante usando la pantalla de búsqueda «Encontrar un Estudiante».</p>';
}
else
	$help['Scheduling/Schedule.php'] = '<p><i>Horario Estudiante</i> muestra el horario de sus estudiantes.</p>';

// GRADES
if(User('PROFILE')=='admin')
{
	$help['Grades/ReportCards.php'] = '<p><i>Boletines de Calificaciones</i> le permite imprimir boletines de calificaciones para cualquier número de estudiantes.</p><p>Usted puede buscar estudiantes que están en un curso especifico haciendo click sobre el enlace «Escoger» al lado de la opción «Curso» y escogiendo un curso desde la ventana emergente que aparece. Usted también puede limitar su búsqueda por promedio, puesto en la clase, y calificación en la Búsqueda Avanzada. Por ejemplo, usted puede buscar los 10 mejores estudiantes de una clase, los estudiantes que fallan.</p><p>También puede escoger imprimir los boletines con etiquetas de correo. Los boletines tendrán etiquetas de correo posicionadas de una manera visible para un sobre con ventana cuando la hoja esta doblada en tercios. Mas de una carta puede ser impreza por estudiante si el estudiante tiene padres residiendo en mas de una dirección.</p><p>Antes de imprimir los boletines, usted debe seleccionar cual periodo a calificar será en el boletín, marcando las casillas de los periodos deseados.</p><p>Los boletines serán automáticamente creados en el formato imprimible PDF cuando usted presione el botón «Crear Boletín de Calificaciones para los Estudiantes Seleccionados».</p>';
	$help['Grades/CalcGPA.php'] = '<p><i>Calcular el Promedio</i> calcula y guarda el promedio y el puesto en la clase de cada estudiante en su institución basado en las calificaciones del periodo a calificar escogido.</p><p>El servicio Calcular el Promedio calcula el promedio ponderado por cada curso multiplicando el dato promedio de la calificación ponderada por el número de créditos. Luego, el divide este dato por el número especifico como escala base de calificaciones. El promedio no ponderado se calcula de la misma manera sino que utiliza la calificación que no es ponderada. Después de calcular el promedio por cada curso, el servicio calcula el promedio del periodo a calificar. El programador clasifica estos datos para determinar el puesto en la clase. Si mas de un estudiante tiene el mismo promedio, ellos van a compartir el mismo puesto.</p>';
	$help['Grades/Transcripts.php'] = '<p><i>Expedientes Académicos</i> le permite imprimir expedientes académicos para cualquier número de estudiantes.</p><p>Usted puede buscar estudiantes que están en un curso especifico haciendo click sobre el enlace «Escoger» al lado de la opción «Curso» y escogiendo un curso desde la ventana emergente que aparece. Usted también puede limitar su búsqueda por promedio, puesto en la clase, y calificación en la Búsqueda Avanzada. Por ejemplo, usted puede buscar los 10 mejores estudiantes de una clase, los estudiantes que fallan.</p><p>Antes de imprimir los expedientes, usted debe seleccionar cuales periodos a calificar serán en el expediente marcando las casillas de los periodos a calificar. También puede escoger incluir la foto del estudiante o los comentarios asociados a cada curso.</p><p>Los expedientes serán automáticamente creados en el formato imprimible PDF cuando usted presione el botón «Crear Expedientes Académicos para los Estudiantes Seleccionados».</p>';
	$help['Grades/TeacherCompletion.php'] = '<p><i>Control Docente</i> es un reporte que muestra cuales docentes no han entrado las calificaciones de cualquier periodo a calificar.</p><p>Las cruces rojas indican que el docente no ha entrado las calificaciones del periodo a calificar actual para esta hora.</p><p>Usted puede seleccionar el bimestre, semestre actual desde el menú desplegable en la parte superior de la pantalla. Para cambiar el bimestre actual, usa el menú desplegable de los periodos a calificar en el marco izquierdo. Usted también puede mostrar solamente una hora escogiendola en el menú desplegable en la parte superior de la pantalla.</p>';
	$help['Grades/GradeBreakdown.php'] = '<p><i>Análisis de Note</i> es un reporte que muestra el número de cada calificación que un docente dio.</p><p>Usted puede seleccionar el bimestre, semestre actual desde el menú desplegable en la parte superior de la pantalla. Para cambiar el bimestre actual, usa el menú desplegable de los periodos a calificar en el marco izquierdo.</p>';
	$help['Grades/StudentGrades.php'] = '<p><i>Calificaciones de los Estudiantes</i> le permite ver las calificaciones de cualquier número de estudiantes.</p><p>Usted puede buscar estudiantes que están en un curso especifico haciendo click sobre el enlace «Escoger» al lado de la opción «Curso» y escogiendo un curso desde la ventana emergente que aparece. Usted también puede limitar su búsqueda por promedio, puesto en la clase, y calificación en la Búsqueda Avanzada. Por ejemplo, usted puede buscar los 10 mejores estudiantes de una clase, los estudiantes que fallan.</p>';
	$help['Grades/GPARankList.php'] = '<p><i>Lista de Promedio / Puesto en la Clase</i> es un reporte que muestra el promedio ponderado, no ponderado, y puesto en la clase de cada estudiante en su institución.</p><p>Como para cada lista en RosarioSIS, usted puede ordenar cualquier dato haciendo click sobre el titulo de la columna en el encabezado. Por ejemplo, usted puede ordenar por grado haciendo click sobre «Grado» en el encabezado.</p>';
}
elseif(User('PROFILE')=='teacher')
{
	$help['Grades/InputFinalGrades.php'] = '<p><i>Entrar Calificaciones Finales</i> le permite entrar las calificaciones del bimestre, semestre para todos sus estudiantes en la clase actual. Por defecto, el servicio lista los estudiantes en su primera clase para el bimestre actual. Usted puede cambiar el bimestre en el menú desplegable en el marco izquierdo. Usted también puede seleccionar el semestre actual en el menú desplegable en la parte superior de la pantalla.</p><p>Una vez que esta en el periodo a calificar deseado, usted puede entrar las calificaciones de los estudiantes seleccionando la calificación para cada estudiante y entrar comentarios si lo desea. Una vez que todos los grados y comentarios están entrados, presione el botón «Guardar» en la parte superior de la pantalla.</p><p>Si usted usa el Libro de Calificaciones, RosarioSIS puede calcular cada calificación del bimestre haciendo click sobre el enlace «Usar la Calificaciones del Libro de Calificaciones» de arriba.</p><p>Si el mensaje «Usted no puede editar estas calificaciones.» aparece, usted no puede entrar las calificaciones finales ese día porque este no se encuentra en el transcurso de publicación de la calificaciones configurado por el periodo a calificar. Ver el servicio Períodos a Calificar para conocer las fechas de publicación de calificaciones.</p>';
	$help['Grades/Configuration.php'] = '<p><i>Libro de Calificaciones - Configuración</i> le permite configurar el libro de calificaciones.</p><p>Usted puede configurar el libro de calificaciones para ponderar las calificaciones de las tareas, ocultar las calificaciones de letra para todas las tareas, calcular Elegibilidad usando las calificaciones, y los porcentajes de la calificación final del semestre.</p>';
	$help['Grades/Assignments.php'] = '<p><i>Libro de Calificaciones - Tareas</i> le permite configurar sus tareas. Hay tipos de tareas y tareas.</p><p>Usted tendrá probablemente tipos de tareas llamados «Trabajo», «Quiz», o «Previa». Los tipos de tareas se crean para cada curso que usted tiene.</p><p>Para agregar un tipo de tarea o una tarea, haga click sobre el icono «+» en la columna deseada. Luego, llene los datos en los campos arriba de las listas y presione el botón «Guardar».</p><p>Si usted marca la casilla «Aplicar a todas las Clases para este Curso», la tarea será asignada a cada clase del curso que usted tiene, de la misma manera que están agregados los tipos de tarea.</p><p>Para cambiar un tipo o una tarea, haga click sobre el tipo o la tarea usted quiere cambiar y luego haga click sobre el dato que usted quiere cambiar en la parte superior de las listas de tareas y tipos. Luego, cambie el dato y presione el botón «Guardar».</p><p>Finalmente, para eliminar una tarea o un tipo, seleccionelo haciendo click sobre su titulo en la lista y presione el botón «Eliminar». Se le preguntará si desea confirmar la eliminación.</p>';
	$help['Grades/Grades.php'] = '<p><i>Libro de Calificaciones - Calificaciones</i> le permite entrar las calificaciones de las tareas para todos sus estudiantes en el periodo a calificar actual. Por defecto, el servicio lista los estudiantes de su primera clase. Usted puede cambiar la clase actual en el menú desplegable del marco izquierdo.</p><p>Una vez que usted ha escogido la clase correcta, usted vera el total de puntos y la calificación ponderada de cada estudiante en su clase. Usted puede ver las calificaciones de una tarea seleccionandola en el menú desplegable de las tareas en la parte superior de la pantalla. Luego, usted puede entrar una nueva calificación entrando los puntos en el campo vacío al lado del nombre del estudiante o usted puede cambiar una calificación existente haciendo click sobre los puntos y cambiando el dato. Después de cambiar las calificaciones, presione el botón «Guardar» en la parte superior de la pantalla.</p><p>Usted también puede ver y cambiar todas las calificaciones de un estudiante haciendo click sobre su nombre en la lista.</p>';
	$help['Grades/ProgressReports.php'] = '<p><i>Libro de Calificaciones - Reportes de Progreso</i> le permite imprimir reportes de progreso para cualquier número de estudiantes.</p><p>Usted puede imprimir reportes de progreso con etiquetas de correo. Los reportes tendrán etiquetas de correo posicionadas de una manera visible para un sobre con ventana cuando la hoja esta doblada en tercios. Mas de una carta puede ser impreza por estudiante si el estudiante tiene padres residiendo en mas de una dirección.</p><p>Los reportes serán automáticamente creados en el formato imprimible PDF cuando usted presione el botón «Crear Reportes de Progreso para los Estudiantes Seleccionados».</p>';
}
else
{
	$help['Grades/ReportCards.php'] = '<p><i>Boletines de Calificaciones</i> le permite imprimir boletines de calificaciones para su estudiante.</p><p>Antes de imprimir el boletín, usted debe seleccionar cuales periodos a calificar estarán en el boletín marcando las casillas de los periodos a calificar deseados.</p><p>El boletín de calificaciones será automáticamente creado en el formato imprimible PDF cuando usted presione el botón «Crear Boletín de Calificaciones para los Estudiantes Seleccionados».</p>';
	$help['Grades/Transcripts.php'] = '<p><i>Expedientes Académicos</i> le permite imprimir expedientes académicos para su estudiante.</p><p>Antes de imprimir el boletín, usted debe seleccionar cuales periodos a calificar estarán en el boletín marcando las casillas de los periodos a calificar deseados.</p><p>Los expedientes académicos serán automáticamente creados en el formato imprimible PDF cuando usted presione el botón «Crear Expedientes Académicos para los Estudiantes Seleccionados».</p>';
	$help['Grades/StudentGrades.php'] = '<p><i>Calificaciones del Libro de Calificaciones</i> le permite ver las calificaciones de su estudiante.</p><p>Usted puede cambiar el periodo a calificar en el menú desplegable del marco izquierdo.</p>';
	$help['Grades/GPARankList.php'] = '<p><i>Promedio / Puesto en la Clase</i> es un reporte que muestra el promedio ponderado y no ponderado, y el puesto en la clase de su estudiante.</p>';
}

// ATTENDANCE
if(User('PROFILE')=='admin')
{
	$help['Attendance/Administration.php'] = '<p><i>Administración</i> le permite ver y cambiar los registros de asistencia de cualquier día.</p><p>Para cambiar el estado de asistencia para cualquier hora, haga click sobre el dato y seleccione el nombre corto del código de asistencia que usted quisiera asociar a este estudiante. Después de hacer las modificaciones, presione el botón «Actualizar». Usted puede limitar la lista de estudiantes escogiendo un código de asistencia en el menú desplegable en la parte superior derecha de la pantalla. Por defecto, todos los estudiantes con cualquier código de estado «Ausente» están listados. Usted puede agregar un código de asistencia haciendo click sobre el icono «+» al lado del menú desplegable de los códigos de asistencia.</p><p>Usted puede cambiar la fecha mostrada haciendo click sobre la fecha en la parte superior izquierda de la pantalla y cambiándola por la fecha deseada.</p><p>Después de cambiar el código de asistencia o la fecha, presione el botón «Actualizar» para refrescar la pantalla con los nuevos parámetros.</p><p>Usted también puede ver el código de asistencia asignado por el docente y también ver y entrar un comentario para cada hora haciendo click sobre el nombre del estudiante.</p><p>Haciendo click sobre el enlace «Estudiante actual» en la parte superior de la pantalla mostrara los registros de asistencia del día para el estudiante actual presente en el marco izquierdo.</p>';
	$help['Attendance/AddAbsences.php'] = '<p><i>Agregar Ausencias</i> le permite agregar una ausencia a un grupo de estudiantes de una vez.</p>Primero, busca estudiantes. Note que usted puede buscar para estudiantes que están tomando un curso específico o están en una actividad especial.</p><p>Desde los resultados de la búsqueda, usted puede seleccionar cualquier número de estudiantes. Usted puede seleccionar todos los estudiantes de la lista marcando la casilla en el encabezado de la lista. Usted también puede especificar las horas, el código de ausencia, la razón de la ausencia, y la fecha.  Finalmente, presione el botón «Guardar» en la parte superior de la pantalla.</p>';
	$help['Attendance/Percent.php'] = '<p><i>Asistencia Diaria Promedio</i> es un reporte que muestra el número de estudiantes, los días posibles, el número de estudiantes presentes por los días posibles, el número de estudiantes ausentes por los días posibles, la Asistencia Diaria Promedio, el número de estudiantes presentes por día promedio, y el número de estudiantes ausentes por día promedio. Estos números están para cada grado.</p><p>Usted puede cambiar el periodo con los menús desplegables de las fechas en la parte superior de la pantalla y presionando el botón «Ir». Usted también puede limitar los números buscando por sexo o cualquier campo de dato haciendo click sobre el enlace «Avanzado».</p>';
	$help['Attendance/Percent.php&list_by_day=true'] = '<p><i>Asistencia Promedio por Día</i> es un reporte que muestra el número de estudiantes, los días posibles, el número de estudiantes presentes por los días posibles, el número de estudiantes ausentes por los días posibles, la Asistencia Diaria Promedio por día, el número de estudiantes presentes por día promedio, y el número de estudiantes ausentes por día promedio. Estos números están para cada grado.</p><p>Usted puede cambiar el periodo con los menús desplegables de las fechas en la parte superior de la pantalla y presionando el botón «Ir». Usted también puede limitar los números buscando por sexo o cualquier campo de dato haciendo click sobre el enlace «Avanzado».</p>';
	$help['Attendance/DailySummary.php'] = '<p><i>Gráfico de Asistencia</i> es un reporte que muestra la asistencia diaria de cualquier número de estudiantes para cada día de un transcurso.</p><p>Después de buscar por estudiantes, usted puede cambiar el periodo con las fechas en los menús desplegables en la parte superior de la pantalla. La lista muestra el dato de asistencia diaria de cada estudiante para cada día con un código de color. Rojo significa ausente todo el día, amarillo significa ausente medio día y verde significa presente todo el día.</p><p>Usted puede ver los registros de asistencia para cada hora, para cualquier estudiante haciendo click sobre el nombre del estudiante. Aquí, el código esta en la casilla de color.</p>';
	$help['Attendance/StudentSummary.php'] = '<p><i>Resumen de la Ausencia</i> es un reporte que muestra los días por lo cuales un estudiante tiene una ausencia.</p><p>Después de seleccionar un estudiante, usted puede cambiar el periodo con las fechas en los menús desplegables en la parte superior de la pantalla y presionando el botón «Ir». La lista muestra las ausencias del estudiante para cada hora de cada día con ausencia. Una cruz roja indica una ausencia por la hora correspondiente.</p>';
	$help['Attendance/TeacherCompletion.php'] = '<p><i>Control Docente</i> es un reporte que muestra cuales docentes no han tomado la asistencia para cualquier día.</p><p>Las cruces rojas indican que un docente no entró la asistencia del día para este periodo.</p><p>Usted puede seleccionar la fecha actual en el menú desplegable en la parte superior de la pantalla. Usted también puede mostrar solamente una hora escogiendola en el menú desplegable de las horas en la parte superior de la pantalla.</p>';
	$help['Attendance/AttendanceCodes.php'] = '<p><i>Códigos de Asistencia</i> le permite configurar los códigos de asistencia de su institución. Los códigos de asistencia son usados en el servicio «Tomar Asistencia» del docente (también como en la mayoría de los reportes de Asistencia) y especifican si el estudiante estaba presente o no durante la hora y si no, la razón.</p><p>Para agregar un código de asistencia, llene el titulo, nombre corto, tipo, y código del estado. Seleccione si el código debería estar o no por defecto para el docente desde los campos vacíos al pié de la lista y presione el botón «Guardar». Si el código de asistencia es del tipo «Oficina Solamente», un docente no será capaz de seleccionarlo desde su servicio «Tomar Asistencia».</p><p>Para cambiar un código de asistencia, haga click sobre cualquier dato del código de asistencia, cambie el dato, y presione el botón «Guardar».</p><p>Para eliminar un código de asistencia, haga click sobre el icono «-» al lado del código de asistencia que quiere eliminar. Se le preguntará si desea confirmar la eliminación.</p>';
}
elseif(User('PROFILE')=='teacher')
	$help['Attendance/TakeAttendance.php'] = '<p><i>Tomar Asistencia</i> le permite entrar la asistencia para todos los estudiantes de la clase actual. Por defecto, el servicio lista los estudiantes de su primera clase. Usted puede cambiar la clase actual en el menú desplegable en el marco izquierdo.</p><p>Una vez que está en la clase correcta, usted puede tomar la asistencia seleccionando el código de asistencia para cada estudiante. Una vez que usted ha tomado la asistencia para todos sus estudiantes, presione el botón «Guardar» en la parte superior de la pantalla.</p>';
else
	$help['Attendance/DailySummary.php'] = '<p><i>Resumen Diario</i> es un reporte que muestra la asistencia diaria de su estudiante durante un transcurso.</p><p>Usted puede modificar el periodo en los menús desplegables de las fechas en la parte superior de la pantalla y presionar el botón «Ir». La lista muestra el dato de la asistencia diaria de su estudiante para cada día con códigos de color. Una caja roja significa que el estudiante estaba ausente ese día, una caja verde que el estudiante estaba presente o tarde ese día. El código de ausencia esta en la caja.</p>';

// ELIGIBILITY
if(User('PROFILE')=='admin')
{
	$help['Eligibility/Student.php'] = '<p><i>Pantalla Estudiante</i> muestra las actividades del estudiante y las calificaciones de elegibilidad del transcurso actual. El servicio le permite también de agregar y eliminar actividades del estudiante.<p>Usted debe primero seleccionar un estudiante usando la pantalla «Encontrar un estudiante». Usted puede buscar estudiantes que están en un curso especifico haciendo click sobre el enlace «Escoger» al lado de la opción «Curso» y escogiendo un curso desde la ventana emergente que aparece. Usted también puede buscar estudiantes que toman una actividad especifica y estudiantes que están inelegibles actualmente. </p><p>Para agregar una actividad a un estudiante, seleccione la actividad deseada en el menú desplegable al lado del icono «+» y presione el botón «Agregar».</p><p>Usted puede especificar el periodo de elegibilidad escogiendo las fechas deseadas en el menú desplegable en la parte superior de la pantalla. Estos periodos se configuran en el servicio «Tiempos de Entrada».</p>';
	$help['Eligibility/AddActivity.php'] = '<p><i>Agregar Actividad</i> le permite agregar una actividad a un grupo de estudiantes de una vez.</p><p>Primero, busca estudiantes. Note que se puede buscar estudiantes que están en una actividad o en un curso especifico. Desde el resultado de la búsqueda, usted puede seleccionar cualquier número de estudiantes. Usted puede seleccionar todos los estudiantes de la lista haciendo click sobre la casilla en el encabezado de la lista. Después de seleccionar los estudiantes, seleccione una actividad en el menú desplegable en la parte superior de la pantalla. Finalmente, presione el botón «Agregar la Actividad a los Estudiantes Seleccionados».</p>';
	$help['Eligibility/Activities.php'] = '<p><i>Actividades</i> le permite configurar las actividades de su institución.</p><p>Para agregar una actividad, llene su titulo, fecha de comienzo y fecha de fin en los campos vacíos al fin de la lista y presione el botón «Guardar».</p><p>Para modificar una actividad, haga click sobre cualquier dato de la actividad, cambie el dato, y presione el botón «Guardar».</p><p>Para eliminar una actividad, haga click sobre el icono «-» al lado de la actividad que quiere eliminar. Se le preguntará si desea confirmar la eliminación.</p>';
	$help['Eligibility/EntryTimes.php'] = '<p><i>Tiempos de Entrada</i> le permite configurar el transcurso semanal durante lo cual docentes pueden entrar la elegibilidad. Docentes deben entrar cada semana en este transcurso. Este transcurso esta usado en el servicio «Entrar Elegibilidad» como en la mayor parte de los reportes de elegibilidad.</p><p>Para cambiar el periodo, simplemente cambie las fechas y presione el botón «Guardar».</p>';
	$help['Eligibility/StudentList.php'] = '<p><i>Lista de Estudiante</i> es un reporte que muestra cada curso y calificación de elegibilidad asignado a cualquier número de estudiantes.</p><p>Después de buscar estudiantes, usted puede especificar el periodo de elegibilidad que quiere ver.  Estos transcursos se configuran en el servicio «Tiempos de Entrada».</p>';
	$help['Eligibility/TeacherCompletion.php'] = '<p><i>Control Docente</i> es un reposte que muestra cuales docentes no han entrado la elegibilidad para cualquier transcurso. Este transcurso se configura en el servicio «Tiempos de Entrada».</p><p>La cruz roja indica que el docente no entró la elegibilidad del periodo actual para esta hora.</p><p>Usted puede seleccionar el periodo actual en el menú desplegable en la parte superior de la pantalla. Usted también puede mostrar solamente una hora escogiendola desde el menú desplegable en la parte superior de la pantalla. Después de seleccionar un transcurso o una hora, presione el botón «Ir» para refrescar la lista.</p>';
}
elseif(User('PROFILE')=='teacher')
	$help['Eligibility/EnterEligibility.php'] = '<p><i>Entrar Elegibilidad</i> le permite entrar las calificaciones de elegibilidad para todos sus estudiantes en la clase actual. Por defecto, el servicio lista los estudiantes de su primera clase. Usted puede cambiar la clase actual en el menú desplegable del marco izquierdo.</p><p>Una vez que esta en la clase correcta, usted puede entrar las calificaciones de elegibilidad seleccionando el código para cada estudiante. Una vez que usted ha entrado la elegibilidad para todos sus estudiantes, presione el botón «Guardar» en la parte superior de la pantalla.</p><p>Si usted usa el Libro de Calificaciones, RosarioSIS puede calcular la elegibilidad de cada estudiante haciendo click sobre el enlace «Usar la Calificaciones del Libro de Calificaciones» de arriba.</p><p>Usted debe entrar la elegibilidad cada semena durante el transcurso especificado por la administración de su institución.</p>';
else
{
	$help['Eligibility/Student.php'] = '<p><i>Pantalla Estudiante</i> muestra las actividades de su estudiante y las calificaciones de elegibilidad del transcurso actual.<p>Usted puede especificar el periodo de elegibilidad que quiere ver escogiendo las fechas en el menú desplegable en la parte superior de la pantalla. La elegibilidad esta entrada cada semana.</p>';
	$help['Eligibility/StudentList.php'] = '<p><i>Lista de Estudiante</i> es un reporte que muestra todas las calificaciones y las calificaciones de elegibilidad de su estudiante.</p><p>Usted puede especificar el transcurso de elegibilidad que quiere ver escogiendo las fechas en el menú desplegable en la parte superior de la pantalla y presionando el botón «Ir». La elegibilidad esta entrada cada semana.</p>';
}

if(mb_strpos($_SERVER['PHP_SELF'],'Help_es.php'))
{
	switch(User('PROFILE'))
	{
		case 'admin':
			$title = 'Administrator';
		break;

		case 'teacher':
			$title = 'Teacher';
		break;

		case 'parent':
			$title = 'Parent';
		break;
		
		case 'parent':
			$title = 'Student';
		break;
	}

	$handle = PDFStart();
	echo '<TABLE><TR><TD><IMG SRC="assets/themes/'.Preferences('THEME').'/logo.png" /></TD><TD><h1>'.sprintf(_('%s Handbook'),$title).'<BR />'.sprintf(_('version %s'),'1.0').'</h1></TD></TR></TABLE><HR>';

	foreach($help as $program=>$value)
	{
		if(mb_strpos($program,'/'))
		{
			$modcat = str_replace('_',' ',mb_substr($program,0,mb_strpos($program,'/')));
			
			if (!$RosarioModules[str_replace(' ','_',$modcat)]) //module not activated
				break;
		
			if($modcat!=$old_modcat)
				echo '<div style="page-break-after: always;"></div><TABLE><TR><TD><IMG SRC="assets/icons/'.str_replace(' ','_',$modcat).'.png"  class="headerIcon" /></TD><TD><h2>'._($modcat).'</h2></TD></TR></TABLE><HR>';
			$old_modcat = $modcat;
		}
		$_REQUEST['modname'] = $program;
		echo '<h3>';
		if($program=='default')
			echo ParseMLField(Config('TITLE')).' - '.sprintf(_('%s Handbook'),$title).'<BR />'.sprintf(_('version %s'),'1.0');
		else
			echo (ProgramTitle() == 'RosarioSIS' ? str_replace(' ','_',$program) : ProgramTitle());
		echo '</h3>';
		echo '<TABLE class="width-100p cellpadding-5"><TR><TD class="header2">';
		/*if($student==true)
			$value = str_replace('your child','yourself',str_replace('your child\'s','your',$value));*/
		echo $value;
		echo '</TD></TR></TABLE><BR />';
	}
	PDFStop($handle);
}
?>